name: test
on:
  push:
    branches:
      - '*'

jobs:
  test-gh-commands:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v2
      - name: Test gh release list 1
        continue-on-error: true
        run: |
          gh release list
      - name: Test gh release list 2
        continue-on-error: true
        run: |
          set -ex
          gh release list --json name
          gh release list --json name --jq '.[].name'
          gh release list --json tagName,name --jq '.[].name + ", " + .[].tagName'
          gh release list --exclude-drafts
      - run: exit 0
      - name: Test gh release view 1
        continue-on-error: true
        run: |
          gh release view 1.0.0
      - name: Test gh release view 2
        continue-on-error: true
        run: |
          gh release view 1.0.0 --json name --jq '.name'
