name: test
on:
  push:
    branches:
      - '*'

jobs:
  test-gh-commands:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v2
      - name: Test gh release list 1
        run: |
          gh release list
      - name: Test gh release list 2
        run: |
          set -ex
          gh release list --json name
          gh release list --json name --jq '.[].name'
          gh release list --json tagName
          gh release list --exclude-drafts
      - name: Test gh release view
        run: |
          gh release view 1.0.0
