name: "Release artifacts"
on:
  release:
    types: [published]
  push:
    tags:
      - '*'

jobs:
  prepare:
    name: "Find release for ${{ github.event.release.tag_name || github.ref_name }}"
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    outputs:
      status: ${{ steps.get_release_tag.outputs.status }}
      tag: ${{ steps.get_release_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
      - name: "Check release for ${{ github.event.release.tag_name || github.ref_name }}"
        id: get_release_tag
        run: |
          set -e
          TAG_NAME=${{ github.event.release.tag_name || github.ref_name }}
          IS_DRAFT=$(gh release view --json isDraft --jq '.isDraft' $TAG_NAME 2>/dev/null) || true
          case "$IS_DRAFT" in
            "true") STATUS="draft" ;;
            "false") STATUS="public" ;;
            *) STATUS="missing" ;;
          esac
          echo "status=$STATUS" >> "$GITHUB_OUTPUT"
          echo "tag=$TAG_NAME" >> "$GITHUB_OUTPUT"

  test-gh-commands:
    name: "Release ${{ needs.prepare.outputs.status }}"
    needs: prepare
    if: ${{ needs.prepare.outputs.status == 'public' }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - run: 'echo "Value from prepare step: .${{ github.event.release.tag_name || github.ref_name }}."'
      - run: |
          set -e
          echo "TAG_NAME=${{ github.event.release.tag_name || github.ref_name }}" >> $GITHUB_ENV
          echo $GITHUB_ENV
          cat $GITHUB_ENV
      - run: 'echo "Tag name: $TAG_NAME"'
      - name: "Tag: $TAG_NAME -- ${{ needs.prepare.outputs.tag }}"
        run: ''
      - uses: actions/checkout@v2
      - name: Test gh release list 1
        continue-on-error: true
        run: |
          gh release list
      - name: Test gh release list 2
        continue-on-error: true
        run: |
          set -ex
          gh release list --json name
          gh release list --json name --jq '.[].name'
          gh release list --json tagName,name --jq '.[].name + ", " + .[].tagName'
          gh release list --exclude-drafts
      - run: exit 0
      - name: Test gh release view 1
        continue-on-error: true
        run: |
          gh release view 1.0.0
      - name: Test gh release view 2
        continue-on-error: true
        run: |
          gh release view 1.0.0 --json name --jq '.name'
